// EDIT THIS LIST TO CHANGE THE WORDS
// Just add or remove words from the array below
let words = [
    'they', 'just', 'you', 'said', 'only', 'full',
    'always', 'once', 'under', 'say', 'and', 'four',
    'look', 'pull', 'who', 'see', 'like', 'for',
    'put', 'does', 'knew', 'those', 'after', 'first',
    'pretty', 'far', 'down', 'she', 'not', 'new',
    'many', 'walk', 'little', 'thank', 'again', 'the',
    'was', 'please', 'because', 'start', 'don\'t', 'done',
    'their', 'laugh', 'should', 'were', 'want', 'by',
    'could', 'give', 'whose', 'think', 'why', 'play',
    'some', 'all', 'know', 'has', 'go', 'two',
    'cold', 'been', 'yours', 'find', 'have', 'every',
    'soon', 'where', 'your', 'come', 'got', 'good',
    'hurt', 'now', 'way', 'had', 'help',
    'these', 'write', 'how', 'live', 'his', 'off',
    'three', 'words', 'any', 'talk', 'her', 'on',
    'use', 'work', 'would', 'here', 'old',
    'there', 'one', 'very', 'from', 'over', 'what'
];

// Short sentences using each word (kid-friendly)
const wordSentences = {
    'they': 'They went to the park.',
    'just': 'I just got home.',
    'you': 'You are my best friend.',
    'said': 'She said hello to me.',
    'only': 'I have only one left.',
    'full': 'The cup is full of water.',
    'always': 'I always brush my teeth.',
    'once': 'Once upon a time.',
    'under': 'The cat is under the bed.',
    'say': 'What did you say?',
    'and': 'I like cats and dogs.',
    'four': 'I have four apples.',
    'look': 'Look at the rainbow!',
    'pull': 'Pull the door open.',
    'who': 'Who is at the door?',
    'see': 'I can see the moon.',
    'like': 'I like ice cream.',
    'for': 'This gift is for you.',
    'put': 'Put it on the table.',
    'does': 'She does her homework.',
    'knew': 'I knew the answer.',
    'those': 'I want those shoes.',
    'after': 'We play after school.',
    'first': 'I was first in line.',
    'pretty': 'The flowers are pretty.',
    'far': 'The store is not far.',
    'down': 'Sit down please.',
    'she': 'She is very kind.',
    'not': 'I am not tired.',
    'new': 'I got a new book.',
    'many': 'There are many stars.',
    'walk': 'Let us walk to school.',
    'little': 'The little bird can sing.',
    'thank': 'Thank you very much.',
    'again': 'Can we play again?',
    'the': 'The sun is bright.',
    'was': 'It was a fun day.',
    'please': 'Please pass the milk.',
    'because': 'I smiled because I was happy.',
    'start': 'Let us start the game.',
    "don't": "I don't like rain.",
    'done': 'I am done with my work.',
    'their': 'Their house is blue.',
    'laugh': 'You make me laugh.',
    'should': 'You should eat your greens.',
    'were': 'They were at the zoo.',
    'want': 'I want to go outside.',
    'by': 'She sat by the window.',
    'could': 'I wish I could fly.',
    'give': 'Please give me a hand.',
    'whose': 'Whose bag is this?',
    'think': 'I think it will rain.',
    'why': 'Why is the sky blue?',
    'play': 'Let us play a game.',
    'some': 'May I have some cake?',
    'all': 'We are all friends.',
    'know': 'I know the way home.',
    'has': 'She has a red hat.',
    'go': 'Let us go to the beach.',
    'two': 'I have two hands.',
    'cold': 'It is cold outside.',
    'been': 'I have been to the zoo.',
    'yours': 'This book is yours.',
    'find': 'Can you find the key?',
    'have': 'I have a dog.',
    'every': 'I read every day.',
    'soon': 'We will be there soon.',
    'where': 'Where are my shoes?',
    'your': 'Your smile is nice.',
    'come': 'Come sit with me.',
    'got': 'I got a gold star.',
    'good': 'You did a good job.',
    'hurt': 'I hurt my knee.',
    'now': 'We should go now.',
    'way': 'This is the way home.',
    'had': 'I had fun today.',
    'help': 'Can you help me?',
    'these': 'I like these colours.',
    'write': 'I will write a letter.',
    'how': 'How are you today?',
    'live': 'I live on a big street.',
    'his': 'His name is Tom.',
    'off': 'Turn off the light.',
    'three': 'I have three cats.',
    'words': 'These words are easy.',
    'any': 'Do you have any pets?',
    'talk': 'Let us talk about it.',
    'her': 'I gave her a flower.',
    'on': 'The book is on the shelf.',
    'use': 'I use a pencil to draw.',
    'work': 'Good work on your test.',
    'would': 'I would like some water.',
    'here': 'Come over here.',
    'old': 'The old tree is tall.',
    'there': 'Look over there!',
    'one': 'I have one wish.',
    'very': 'You are very smart.',
    'from': 'I am from this town.',
    'over': 'Jump over the puddle.',
    'what': 'What is your name?'
};

// Basics list: numbers, days, months, colors
const basicsWords = [
    // Numbers
    'zero', 'one', 'two', 'three', 'four', 'five',
    'six', 'seven', 'eight', 'nine', 'ten',
    'eleven', 'twelve', 'thirteen', 'fourteen', 'fifteen',
    'sixteen', 'seventeen', 'eighteen', 'nineteen', 'twenty',
    // Days
    'Monday', 'Tuesday', 'Wednesday', 'Thursday',
    'Friday', 'Saturday', 'Sunday',
    // Months
    'January', 'February', 'March', 'April',
    'May', 'June', 'July', 'August',
    'September', 'October', 'November', 'December',
    // Colors
    'red', 'blue', 'green', 'yellow', 'orange',
    'purple', 'pink', 'black', 'white', 'brown',
    'gray', 'gold', 'silver'
];

const basicsSentences = {
    // Numbers
    'zero': 'The score is zero to one.',
    'one': 'I have one wish.',
    'two': 'I have two hands.',
    'three': 'I have three cats.',
    'four': 'I have four apples.',
    'five': 'I have five fingers.',
    'six': 'There are six eggs in the box.',
    'seven': 'There are seven days in a week.',
    'eight': 'The spider has eight legs.',
    'nine': 'I wake up at nine o\'clock.',
    'ten': 'I can count to ten.',
    'eleven': 'There are eleven players on a soccer team.',
    'twelve': 'There are twelve months in a year.',
    'thirteen': 'I am thirteen years old.',
    'fourteen': 'There are fourteen days in two weeks.',
    'fifteen': 'We have fifteen minutes left.',
    'sixteen': 'She got sixteen candles on her cake.',
    'seventeen': 'There are seventeen kids in my class.',
    'eighteen': 'He scored eighteen points.',
    'nineteen': 'There are nineteen birds on the tree.',
    'twenty': 'I counted twenty stars.',
    // Days
    'Monday': 'Monday is the first day of the week.',
    'Tuesday': 'We have art class on Tuesday.',
    'Wednesday': 'Wednesday is in the middle of the week.',
    'Thursday': 'Thursday comes before Friday.',
    'Friday': 'Friday is my favourite day.',
    'Saturday': 'We go to the park on Saturday.',
    'Sunday': 'Sunday is a day of rest.',
    // Months
    'January': 'January is the first month of the year.',
    'February': 'February is the shortest month.',
    'March': 'March winds blow the leaves around.',
    'April': 'April showers bring May flowers.',
    'May': 'May is a beautiful month.',
    'June': 'School ends in June.',
    'July': 'We watch fireworks in July.',
    'August': 'August is very hot.',
    'September': 'September is when school starts.',
    'October': 'October has Halloween.',
    'November': 'November leaves turn brown.',
    'December': 'December has Christmas.',
    // Colors
    'red': 'The red apple is sweet.',
    'blue': 'The sky is blue today.',
    'green': 'The green grass is soft.',
    'yellow': 'The yellow sun is bright.',
    'orange': 'I ate an orange for lunch.',
    'purple': 'She wore a purple dress.',
    'pink': 'The pink flowers smell nice.',
    'black': 'The black cat sat on the mat.',
    'white': 'The white snow is cold.',
    'brown': 'The brown dog is friendly.',
    'gray': 'The gray clouds mean rain.',
    'gold': 'She won a gold medal.',
    'silver': 'The silver moon is bright.'
};

// Merge basics sentences into wordSentences so lookups work for all lists
Object.assign(wordSentences, basicsSentences);
