// EDIT THIS LIST TO CHANGE THE WORDS
// Just add or remove words from the array below
let words = [
    'they', 'just', 'you', 'said', 'only', 'full',
    'always', 'once', 'under', 'say', 'and', 'four',
    'look', 'pull', 'who', 'see', 'like', 'for',
    'put', 'does', 'knew', 'those', 'after', 'first',
    'pretty', 'far', 'down', 'she', 'not', 'new',
    'many', 'walk', 'little', 'thank', 'again', 'the',
    'was', 'please', 'because', 'start', 'don\'t', 'done',
    'their', 'laugh', 'should', 'were', 'want', 'by',
    'could', 'give', 'whose', 'think', 'why', 'play',
    'some', 'all', 'know', 'has', 'go', 'two',
    'cold', 'been', 'yours', 'find', 'have', 'every',
    'soon', 'where', 'your', 'come', 'got', 'good',
    'hurt', 'now', 'way', 'had', 'help',
    'these', 'write', 'how', 'live', 'his', 'off',
    'three', 'words', 'any', 'talk', 'her', 'on',
    'use', 'work', 'would', 'here', 'old',
    'there', 'one', 'very', 'from', 'over', 'what'
];

// Short sentences using each word (kid-friendly)
const wordSentences = {
    'they': 'They went to the park.',
    'just': 'I just got home.',
    'you': 'You are my best friend.',
    'said': 'She said hello to me.',
    'only': 'I have only one left.',
    'full': 'The cup is full of water.',
    'always': 'I always brush my teeth.',
    'once': 'Once upon a time.',
    'under': 'The cat is under the bed.',
    'say': 'What did you say?',
    'and': 'I like cats and dogs.',
    'four': 'I have four apples.',
    'look': 'Look at the rainbow!',
    'pull': 'Pull the door open.',
    'who': 'Who is at the door?',
    'see': 'I can see the moon.',
    'like': 'I like ice cream.',
    'for': 'This gift is for you.',
    'put': 'Put it on the table.',
    'does': 'She does her homework.',
    'knew': 'I knew the answer.',
    'those': 'I want those shoes.',
    'after': 'We play after school.',
    'first': 'I was first in line.',
    'pretty': 'The flowers are pretty.',
    'far': 'The store is not far.',
    'down': 'Sit down please.',
    'she': 'She is very kind.',
    'not': 'I am not tired.',
    'new': 'I got a new book.',
    'many': 'There are many stars.',
    'walk': 'Let us walk to school.',
    'little': 'The little bird can sing.',
    'thank': 'Thank you very much.',
    'again': 'Can we play again?',
    'the': 'The sun is bright.',
    'was': 'It was a fun day.',
    'please': 'Please pass the milk.',
    'because': 'I smiled because I was happy.',
    'start': 'Let us start the game.',
    "don't": "I don't like rain.",
    'done': 'I am done with my work.',
    'their': 'Their house is blue.',
    'laugh': 'You make me laugh.',
    'should': 'You should eat your greens.',
    'were': 'They were at the zoo.',
    'want': 'I want to go outside.',
    'by': 'She sat by the window.',
    'could': 'I wish I could fly.',
    'give': 'Please give me a hand.',
    'whose': 'Whose bag is this?',
    'think': 'I think it will rain.',
    'why': 'Why is the sky blue?',
    'play': 'Let us play a game.',
    'some': 'May I have some cake?',
    'all': 'We are all friends.',
    'know': 'I know the way home.',
    'has': 'She has a red hat.',
    'go': 'Let us go to the beach.',
    'two': 'I have two hands.',
    'cold': 'It is cold outside.',
    'been': 'I have been to the zoo.',
    'yours': 'This book is yours.',
    'find': 'Can you find the key?',
    'have': 'I have a dog.',
    'every': 'I read every day.',
    'soon': 'We will be there soon.',
    'where': 'Where are my shoes?',
    'your': 'Your smile is nice.',
    'come': 'Come sit with me.',
    'got': 'I got a gold star.',
    'good': 'You did a good job.',
    'hurt': 'I hurt my knee.',
    'now': 'We should go now.',
    'way': 'This is the way home.',
    'had': 'I had fun today.',
    'help': 'Can you help me?',
    'these': 'I like these colours.',
    'write': 'I will write a letter.',
    'how': 'How are you today?',
    'live': 'I live on a big street.',
    'his': 'His name is Tom.',
    'off': 'Turn off the light.',
    'three': 'I have three cats.',
    'words': 'These words are easy.',
    'any': 'Do you have any pets?',
    'talk': 'Let us talk about it.',
    'her': 'I gave her a flower.',
    'on': 'The book is on the shelf.',
    'use': 'I use a pencil to draw.',
    'work': 'Good work on your test.',
    'would': 'I would like some water.',
    'here': 'Come over here.',
    'old': 'The old tree is tall.',
    'there': 'Look over there!',
    'one': 'I have one wish.',
    'very': 'You are very smart.',
    'from': 'I am from this town.',
    'over': 'Jump over the puddle.',
    'what': 'What is your name?'
};

// Numbers list (zero to ten)
const numbersWords = [
    'zero', 'one', 'two', 'three', 'four', 'five',
    'six', 'seven', 'eight', 'nine', 'ten'
];

// Days list
const daysWords = [
    'Monday', 'Tuesday', 'Wednesday', 'Thursday',
    'Friday', 'Saturday', 'Sunday'
];

// Months list
const monthsWords = [
    'January', 'February', 'March', 'April',
    'May', 'June', 'July', 'August',
    'September', 'October', 'November', 'December'
];

const extraSentences = {
    'zero': 'The score is zero to one.',
    'one': 'I have one wish.',
    'two': 'I have two hands.',
    'three': 'I have three cats.',
    'four': 'I have four apples.',
    'five': 'I have five fingers.',
    'six': 'There are six eggs in the box.',
    'seven': 'There are seven days in a week.',
    'eight': 'The spider has eight legs.',
    'nine': 'I wake up at nine o\'clock.',
    'ten': 'I can count to ten.',
    'Monday': 'Monday is the first day of the week.',
    'Tuesday': 'We have art class on Tuesday.',
    'Wednesday': 'Wednesday is in the middle of the week.',
    'Thursday': 'Thursday comes before Friday.',
    'Friday': 'Friday is my favourite day.',
    'Saturday': 'We go to the park on Saturday.',
    'Sunday': 'Sunday is a day of rest.',
    'January': 'January is the first month of the year.',
    'February': 'February is the shortest month.',
    'March': 'March winds blow the leaves around.',
    'April': 'April showers bring May flowers.',
    'May': 'May is a beautiful month.',
    'June': 'School ends in June.',
    'July': 'We watch fireworks in July.',
    'August': 'August is very hot.',
    'September': 'September is when school starts.',
    'October': 'October has Halloween.',
    'November': 'November leaves turn brown.',
    'December': 'December has Christmas.'
};

// Common Sight Words (Fry 300 minus Red Card Words)
const sightWords = [
    'of', 'a', 'to', 'in', 'is', 'that', 'it', 'he',
    'are', 'as', 'with', 'at', 'be', 'this', 'or',
    'word', 'but', 'we', 'when', 'can', 'an', 'each',
    'which', 'do', 'if', 'will', 'up', 'other', 'about',
    'out', 'then', 'them', 'so', 'him', 'into', 'time',
    'more', 'number', 'no', 'people', 'my', 'than',
    'water', 'call', 'oil', 'long', 'day', 'did', 'get',
    'made', 'may', 'part', 'sound', 'take', 'place',
    'year', 'me', 'back', 'most', 'thing', 'our', 'name',
    'sentence', 'man', 'great', 'through', 'much', 'before',
    'line', 'right', 'too', 'mean', 'same', 'tell', 'boy',
    'follow', 'came', 'show', 'also', 'around', 'farm',
    'small', 'set', 'end', 'another', 'well', 'large',
    'must', 'big', 'even', 'such', 'turn', 'ask', 'went',
    'men', 'read', 'need', 'land', 'different', 'home',
    'us', 'move', 'try', 'kind', 'hand', 'picture',
    'change', 'spell', 'air', 'away', 'animal', 'house',
    'point', 'page', 'letter', 'mother', 'answer', 'found',
    'study', 'still', 'learn', 'world', 'high', 'near',
    'add', 'food', 'between', 'own', 'below', 'country',
    'plant', 'last', 'school', 'father', 'keep', 'tree',
    'never', 'city', 'earth', 'eye', 'light', 'thought',
    'head', 'story', 'saw', 'left', 'few', 'while',
    'along', 'might', 'close', 'something', 'seem', 'next',
    'hard', 'open', 'example', 'begin', 'life', 'both',
    'paper', 'together', 'group', 'often', 'run', 'important',
    'until', 'children', 'side', 'feet', 'car', 'mile',
    'night', 'white', 'sea', 'began', 'grow', 'took',
    'river', 'carry', 'state', 'book', 'hear', 'stop',
    'without', 'second', 'late', 'miss', 'idea', 'enough',
    'eat', 'face', 'watch', 'real', 'almost', 'let',
    'above', 'girl', 'sometimes', 'mountain', 'cut', 'young',
    'list', 'song', 'being', 'leave', 'family', "it\'s",
    'afternoon'
];

const sightSentences = {
    'of': 'I have a cup of water.',
    'a': 'I saw a bird in the tree.',
    'to': 'I like to run fast.',
    'in': 'The toy is in the box.',
    'is': 'She is my best friend.',
    'that': 'I like that book.',
    'it': 'It is sunny outside.',
    'he': 'He can run very fast.',
    'are': 'We are going to the park.',
    'as': 'She is as tall as me.',
    'with': 'I play with my friend.',
    'at': 'We are at the shop.',
    'be': 'I want to be a doctor.',
    'this': 'This is my favourite toy.',
    'or': 'Do you want milk or juice?',
    'word': 'Can you spell that word?',
    'but': 'I tried but I could not.',
    'we': 'We are having fun.',
    'when': 'When is your birthday?',
    'can': 'I can ride a bike.',
    'an': 'I ate an apple.',
    'each': 'Each child got a prize.',
    'which': 'Which one do you want?',
    'do': 'What do you like to eat?',
    'if': 'If it rains we stay inside.',
    'will': 'I will go tomorrow.',
    'up': 'Look up at the sky.',
    'other': 'The other team won.',
    'about': 'Tell me about your day.',
    'out': 'Let us go out to play.',
    'then': 'First eat, then play.',
    'them': 'I gave them a gift.',
    'so': 'I was so happy today.',
    'him': 'I told him a joke.',
    'into': 'She jumped into the pool.',
    'time': 'What time is it?',
    'more': 'Can I have more please?',
    'number': 'Pick a number from one to ten.',
    'no': 'No, thank you.',
    'people': 'Many people came to the party.',
    'my': 'This is my dog.',
    'than': 'She is taller than me.',
    'water': 'I drink lots of water.',
    'call': 'Call me when you get home.',
    'oil': 'We cook with oil.',
    'long': 'The snake is very long.',
    'day': 'It was a lovely day.',
    'did': 'I did my homework.',
    'get': 'I will get my bag.',
    'made': 'She made a cake.',
    'may': 'May I go outside?',
    'part': 'I like this part of the story.',
    'sound': 'What is that sound?',
    'take': 'Take your coat with you.',
    'place': 'This is a nice place.',
    'year': 'I am seven years old.',
    'me': 'Come with me.',
    'back': 'I will be right back.',
    'most': 'She has the most stickers.',
    'thing': 'The best thing is recess.',
    'our': 'This is our classroom.',
    'name': 'What is your name?',
    'sentence': 'Write a sentence about your pet.',
    'man': 'The man walked his dog.',
    'great': 'You did a great job!',
    'through': 'We walked through the forest.',
    'much': 'Thank you very much.',
    'before': 'Wash your hands before you eat.',
    'line': 'Stand in a straight line.',
    'right': 'You got the right answer.',
    'too': 'I want to come too!',
    'mean': 'What does that word mean?',
    'same': 'We have the same shoes.',
    'tell': 'Tell me a story.',
    'boy': 'The boy kicked the ball.',
    'follow': 'Follow me to the garden.',
    'came': 'She came to my party.',
    'show': 'Show me your drawing.',
    'also': 'I also like pizza.',
    'around': 'We ran around the park.',
    'farm': 'The farm has many animals.',
    'small': 'The mouse is very small.',
    'set': 'Set the table for dinner.',
    'end': 'This is the end of the story.',
    'another': 'Can I have another turn?',
    'well': 'She sings very well.',
    'large': 'The elephant is very large.',
    'must': 'You must brush your teeth.',
    'big': 'I have a big smile.',
    'even': 'I can even do a cartwheel.',
    'such': 'It was such a fun day.',
    'turn': 'It is your turn now.',
    'ask': 'Ask the teacher for help.',
    'went': 'We went to the zoo.',
    'men': 'The men fixed the road.',
    'read': 'I love to read books.',
    'need': 'I need a pencil.',
    'land': 'The plane will land soon.',
    'different': 'We are all different.',
    'home': 'I walked home from school.',
    'us': 'Come sit with us.',
    'move': 'Please move your chair.',
    'try': 'Try your best!',
    'kind': 'She is very kind.',
    'hand': 'Raise your hand to answer.',
    'picture': 'Draw a picture of your family.',
    'change': 'The leaves change colour.',
    'spell': 'Can you spell your name?',
    'air': 'The fresh air feels nice.',
    'away': 'The bird flew away.',
    'animal': 'My favourite animal is a dog.',
    'house': 'Our house is on a big street.',
    'point': 'Point to the right answer.',
    'page': 'Turn to the next page.',
    'letter': 'I wrote a letter to my friend.',
    'mother': 'My mother reads to me.',
    'answer': 'I know the answer!',
    'found': 'I found a shell on the beach.',
    'study': 'I study spelling every day.',
    'still': 'Please sit still.',
    'learn': 'I want to learn to swim.',
    'world': 'The world is a big place.',
    'high': 'The kite flew very high.',
    'near': 'The shop is near our house.',
    'add': 'Add the numbers together.',
    'food': 'The food smells great.',
    'between': 'Sit between your friends.',
    'own': 'I have my own room.',
    'below': 'The fish swam below the boat.',
    'country': 'We live in a big country.',
    'plant': 'We plant seeds in spring.',
    'last': 'I was last in line.',
    'school': 'I like going to school.',
    'father': 'My father reads the paper.',
    'keep': 'Keep your desk tidy.',
    'tree': 'The tree is very tall.',
    'never': 'I have never seen snow.',
    'city': 'The city has tall buildings.',
    'earth': 'The earth goes around the sun.',
    'eye': 'She has a blue eye.',
    'light': 'Turn on the light please.',
    'thought': 'I thought about it all day.',
    'head': 'Put a hat on your head.',
    'story': 'Read me a bedtime story.',
    'saw': 'I saw a rainbow today.',
    'left': 'Turn left at the corner.',
    'few': 'I have a few coins.',
    'while': 'Wait here for a while.',
    'along': 'Walk along the path.',
    'might': 'It might rain later.',
    'close': 'Close the door please.',
    'something': 'I want something to eat.',
    'seem': 'You seem happy today.',
    'next': 'You are next in line.',
    'hard': 'The test was hard.',
    'open': 'Open your book to page five.',
    'example': 'Show me an example.',
    'begin': 'Let us begin the lesson.',
    'life': 'I love my life.',
    'both': 'Both of us like ice cream.',
    'paper': 'Write on the paper.',
    'together': 'We play together every day.',
    'group': 'Our group finished first.',
    'often': 'I often ride my bike.',
    'run': 'I like to run at recess.',
    'important': 'It is important to be kind.',
    'until': 'Wait until I get back.',
    'children': 'The children played outside.',
    'side': 'Stand on this side.',
    'feet': 'My feet are cold.',
    'car': 'We drove the car to the shop.',
    'mile': 'We walked a whole mile.',
    'night': 'The stars shine at night.',
    'white': 'The white rabbit hopped away.',
    'sea': 'The sea is blue and wide.',
    'began': 'The show began at noon.',
    'grow': 'Plants grow in the sun.',
    'took': 'She took her bag to school.',
    'river': 'The river flows to the sea.',
    'carry': 'Can you carry this box?',
    'state': 'What state do you live in?',
    'book': 'I read a book every night.',
    'hear': 'I can hear the birds singing.',
    'stop': 'Stop at the red light.',
    'without': 'I went out without my coat.',
    'second': 'I came in second place.',
    'late': 'Do not be late for school.',
    'miss': 'I miss my grandma.',
    'idea': 'That is a great idea!',
    'enough': 'I have had enough to eat.',
    'eat': 'It is time to eat lunch.',
    'face': 'She has a happy face.',
    'watch': 'Watch me do a trick!',
    'real': 'Is that a real butterfly?',
    'almost': 'I am almost done.',
    'let': 'Let me help you.',
    'above': 'The clouds are above us.',
    'girl': 'The girl won the race.',
    'sometimes': 'Sometimes I stay up late.',
    'mountain': 'The mountain is very tall.',
    'cut': 'Cut along the dotted line.',
    'young': 'The young puppy is playful.',
    'list': 'Write a list of your friends.',
    'song': 'Sing me a song.',
    'being': 'Thank you for being my friend.',
    'leave': 'I leave for school at eight.',
    'family': 'I love my family.',
    "it\'s": "It\'s a beautiful day.",
    'afternoon': 'We play in the afternoon.'
};

// St Thomas word list
const stThomasWords = [
    // Spelling test words
    'pride', 'broke', 'cry', 'friend', 'great', 'drool',
    // Weather Conditions
    'sunny', 'cloudy', 'partly cloudy', 'overcast', 'rainy', 'windy',
    'stormy', 'snowy', 'foggy', 'breezy', 'icy', 'chilly',
    'hot', 'cold', 'warm', 'freezing', 'shady',
    // Extreme Weather & Natural Events
    'thunderstorm', 'heatwave', 'hurricane', 'tornado', 'cyclone',
    'typhoon', 'drought', 'gust', 'cold front', 'warm front',
    // Temperature & Air
    'temperature', 'fahrenheit', 'celsius', 'air pressure', 'humidity',
    // Weather Tools & Instruments
    'thermometer', 'barometer', 'anemometer', 'rain gauge',
    'weathervane', 'hygrometer', 'weather balloon', 'satellite',
    // Weather Science Concepts
    'forecast', 'atmosphere', 'climate', 'season',
    'precipitation', 'evaporation', 'condensation',
    // Types of Precipitation
    'rainstorm', 'downpour', 'drizzle', 'flurries', 'snow',
    'blizzard', 'sleet', 'hail', 'mist', 'frost',
    // Weather Phenomena
    'thunder', 'lightning', 'rainbow', 'dew',
    // Weather Professions
    'meteorologist', 'weather reporter', 'storm chaser',
    'climatologist', 'environmental scientist',
    // Compound Words
    'firefly', 'baseball', 'inchworm', 'cupcake',
    'hairbrush', 'airport', 'necklace', 'eyebrow'
];

const stThomasSentences = {
    // Spelling test words
    'pride': 'She felt pride after finishing the race.',
    'broke': 'The cup broke when it fell.',
    'cry': 'The baby started to cry.',
    'friend': 'My best friend lives next door.',
    'great': 'You did a great job today!',
    'drool': 'The dog started to drool over the bone.',
    // Weather Conditions
    'sunny': 'It is a sunny day outside.',
    'cloudy': 'The sky is cloudy today.',
    'partly cloudy': 'The weather is partly cloudy this morning.',
    'overcast': 'The sky was overcast all day.',
    'rainy': 'We stayed inside on the rainy day.',
    'windy': 'It is very windy at the beach.',
    'stormy': 'The stormy weather kept us at home.',
    'snowy': 'The snowy mountains looked beautiful.',
    'foggy': 'It was so foggy we could not see the road.',
    'breezy': 'A breezy afternoon is perfect for flying kites.',
    'icy': 'The roads are icy in winter.',
    'chilly': 'It was chilly outside this morning.',
    'hot': 'It was very hot in the summer.',
    'cold': 'The cold wind made me shiver.',
    'warm': 'The warm sun feels nice on my skin.',
    'freezing': 'The freezing rain turned to ice.',
    'shady': 'We sat under the shady tree.',
    // Extreme Weather & Natural Events
    'thunderstorm': 'A loud thunderstorm woke me up last night.',
    'heatwave': 'The heatwave lasted for a whole week.',
    'hurricane': 'The hurricane brought strong winds and rain.',
    'tornado': 'A tornado can spin very fast.',
    'cyclone': 'The cyclone moved across the ocean.',
    'typhoon': 'A typhoon is a big storm over the sea.',
    'drought': 'The drought made the ground very dry.',
    'gust': 'A strong gust of wind blew my hat away.',
    'cold front': 'A cold front is coming tomorrow.',
    'warm front': 'The warm front will bring rain later.',
    // Temperature & Air
    'temperature': 'The temperature dropped below zero.',
    'fahrenheit': 'In America they measure heat in fahrenheit.',
    'celsius': 'Water boils at one hundred degrees celsius.',
    'air pressure': 'The air pressure changes before a storm.',
    'humidity': 'The humidity makes the air feel sticky.',
    // Weather Tools & Instruments
    'thermometer': 'A thermometer measures the temperature.',
    'barometer': 'A barometer measures air pressure.',
    'anemometer': 'An anemometer measures how fast the wind blows.',
    'rain gauge': 'A rain gauge measures how much rain falls.',
    'weathervane': 'The weathervane shows which way the wind blows.',
    'hygrometer': 'A hygrometer measures the humidity in the air.',
    'weather balloon': 'A weather balloon floats high into the sky.',
    'satellite': 'A satellite takes pictures of the Earth from space.',
    // Weather Science Concepts
    'forecast': 'The forecast says it will rain tomorrow.',
    'atmosphere': 'The atmosphere is the air around the Earth.',
    'climate': 'The climate near the equator is very warm.',
    'season': 'Summer is my favourite season.',
    'precipitation': 'Rain and snow are types of precipitation.',
    'evaporation': 'Evaporation turns water into gas.',
    'condensation': 'Condensation forms droplets on a cold glass.',
    // Types of Precipitation
    'rainstorm': 'The rainstorm flooded the streets.',
    'downpour': 'We got soaked in the sudden downpour.',
    'drizzle': 'A light drizzle fell all morning.',
    'flurries': 'Snow flurries danced in the wind.',
    'snow': 'The snow covered the ground in white.',
    'blizzard': 'The blizzard brought heavy snow and strong winds.',
    'sleet': 'Sleet is a mix of rain and ice.',
    'hail': 'The hail was as big as marbles.',
    'mist': 'A thin mist hung over the lake.',
    'frost': 'Frost covered the windows this morning.',
    // Weather Phenomena
    'thunder': 'We heard loud thunder after the lightning.',
    'lightning': 'Lightning lit up the sky.',
    'rainbow': 'A beautiful rainbow appeared after the rain.',
    'dew': 'The grass was covered in morning dew.',
    // Weather Professions
    'meteorologist': 'A meteorologist studies the weather.',
    'weather reporter': 'The weather reporter said it will be sunny.',
    'storm chaser': 'A storm chaser follows tornadoes.',
    'climatologist': 'A climatologist studies climate patterns.',
    'environmental scientist': 'An environmental scientist protects the planet.',
    // Compound Words
    'firefly': 'The firefly lit up the dark garden.',
    'baseball': 'We played baseball at the park.',
    'inchworm': 'The inchworm crawled along the leaf.',
    'cupcake': 'I had a chocolate cupcake for dessert.',
    'hairbrush': 'I used a hairbrush to fix my hair.',
    'airport': 'We went to the airport to catch our plane.',
    'necklace': 'She wore a pretty necklace to the party.',
    'eyebrow': 'He raised one eyebrow in surprise.'
};

// Greek & Latin Roots word list
const greekRootsWords = [
    // Vocabulary words
    'monarchy', 'oligarchy', 'acropolis', 'democracy', 'mythology',
    // Prefixes & suffixes
    'mono', 'logy',
    // Bases
    'demos', 'oligo', 'cracy', 'archy', 'acros', 'polis', 'myth'
];

const greekRootsSentences = {
    // Vocabulary words
    'monarchy': 'The word monarchy means ruling of one.',
    'oligarchy': 'The word oligarchy means ruling of few.',
    'acropolis': 'The word acropolis means the highest in the city.',
    'democracy': 'The word democracy means common people rule.',
    'mythology': 'The word mythology means a collection or study of stories.',
    // Prefixes & suffixes
    'mono': 'The prefix mono means one or alone.',
    'logy': 'The suffix logy means a collection or study of something.',
    // Bases
    'demos': 'The base demos means common people.',
    'oligo': 'The base oligo means few.',
    'cracy': 'The base cracy means rule.',
    'archy': 'The base archy also means rule.',
    'acros': 'The base acros means highest.',
    'polis': 'The base polis means city.',
    'myth': 'A myth is a traditional story passed down through history.'
};

// Transition Words list
const transitionWords = [
    // Beginning
    'as soon as', 'at first', 'at the beginning', 'before', 'earlier',
    'early on', 'first', 'first of all', 'initially',
    'in the beginning', 'in the first place', 'in the past',
    'it started when', 'not long ago', 'once upon a time',
    'one day', 'one early morning', 'one night', 'one evening',
    'one sunny day', 'one time', 'to begin', 'to start', 'yesterday',
    // Middle
    'a few minutes later', 'after that', 'all of a sudden',
    'before long', 'during', 'eventually', 'in addition',
    'in the meantime', 'later that day', 'meanwhile', 'momentarily',
    'next week', 'not long after', 'occasionally', 'right after',
    'second', 'shortly after', 'soon after', 'therefore', 'third',
    'tomorrow', 'until that time',
    // End
    'all in all', 'as a result', 'at last', 'at the end',
    'by the end', 'consequently', 'finally', 'hereafter',
    'in conclusion', 'in the end', 'in summary',
    'last but not least', 'last of all', 'lastly', 'later on',
    'overall', 'thereafter', 'to end', 'to conclude',
    'to finish', 'to sum it all up', 'ultimately'
];

const transitionSentences = {
    // Beginning
    'as soon as': 'As soon as the bell rang we ran outside.',
    'at first': 'At first I was scared of the dark.',
    'at the beginning': 'At the beginning of the story the hero was lost.',
    'before': 'Before school I eat my breakfast.',
    'earlier': 'Earlier today I finished my homework.',
    'early on': 'Early on we knew it would be a great day.',
    'first': 'First I brush my teeth.',
    'first of all': 'First of all let me say thank you.',
    'initially': 'Initially the puzzle seemed impossible.',
    'in the beginning': 'In the beginning there was nothing but darkness.',
    'in the first place': 'In the first place you should listen carefully.',
    'in the past': 'In the past people wrote letters by hand.',
    'it started when': 'It started when the lights went out.',
    'not long ago': 'Not long ago we moved to a new house.',
    'once upon a time': 'Once upon a time there lived a brave knight.',
    'one day': 'One day I found a golden coin.',
    'one early morning': 'One early morning the rooster crowed loudly.',
    'one night': 'One night we saw shooting stars.',
    'one evening': 'One evening we had a family picnic.',
    'one sunny day': 'One sunny day we went to the beach.',
    'one time': 'One time I saw a deer in my garden.',
    'to begin': 'To begin please open your books.',
    'to start': 'To start the game press the green button.',
    'yesterday': 'Yesterday we had a great time at the park.',
    // Middle
    'a few minutes later': 'A few minutes later the bus arrived.',
    'after that': 'After that we went home for dinner.',
    'all of a sudden': 'All of a sudden it started to rain.',
    'before long': 'Before long the sun came out again.',
    'during': 'During the movie I ate popcorn.',
    'eventually': 'Eventually we found the lost puppy.',
    'in addition': 'In addition to reading I also like writing.',
    'in the meantime': 'In the meantime you can draw a picture.',
    'later that day': 'Later that day we visited our grandparents.',
    'meanwhile': 'Meanwhile the cat was sleeping on the couch.',
    'momentarily': 'The lights flickered momentarily during the storm.',
    'next week': 'Next week we have a school trip.',
    'not long after': 'Not long after we left it started to snow.',
    'occasionally': 'Occasionally we get ice cream after dinner.',
    'right after': 'Right after lunch we went to the playground.',
    'second': 'Second you need to add the eggs.',
    'shortly after': 'Shortly after breakfast we left for school.',
    'soon after': 'Soon after the game ended we celebrated.',
    'therefore': 'It was raining therefore we stayed inside.',
    'third': 'Third mix everything together.',
    'tomorrow': 'Tomorrow is going to be a wonderful day.',
    'until that time': 'Until that time I had never seen the ocean.',
    // End
    'all in all': 'All in all it was a fantastic trip.',
    'as a result': 'As a result we won the competition.',
    'at last': 'At last the train arrived at the station.',
    'at the end': 'At the end of the story everyone was happy.',
    'by the end': 'By the end of the day I was very tired.',
    'consequently': 'He forgot his umbrella and consequently got wet.',
    'finally': 'Finally we reached the top of the mountain.',
    'hereafter': 'Hereafter I will always remember this day.',
    'in conclusion': 'In conclusion reading is important for everyone.',
    'in the end': 'In the end we all agreed it was worth it.',
    'in summary': 'In summary the project was a big success.',
    'last but not least': 'Last but not least I want to thank my teacher.',
    'last of all': 'Last of all we sang a song together.',
    'lastly': 'Lastly do not forget to turn off the lights.',
    'later on': 'Later on we watched a movie at home.',
    'overall': 'Overall it was a wonderful experience.',
    'thereafter': 'Thereafter everything went smoothly.',
    'to end': 'To end the show we took a bow.',
    'to conclude': 'To conclude I believe we can do better.',
    'to finish': 'To finish add some sprinkles on top.',
    'to sum it all up': 'To sum it all up we had an amazing year.',
    'ultimately': 'Ultimately the team worked together and won.'
};

// Merge extra sentences into wordSentences so lookups work for all lists
Object.assign(wordSentences, extraSentences);
Object.assign(wordSentences, sightSentences);
Object.assign(wordSentences, stThomasSentences);
Object.assign(wordSentences, transitionSentences);
Object.assign(wordSentences, greekRootsSentences);

// Root-part highlighting for Greek & Latin Roots vocabulary words
// Each entry defines two parts: first root (primary/red) and second root (secondary/blue)
const greekRootHighlights = {
    'monarchy':  [{ text: 'mon',  cls: 'root-primary' }, { text: 'archy', cls: 'root-secondary' }],
    'oligarchy': [{ text: 'olig', cls: 'root-primary' }, { text: 'archy', cls: 'root-secondary' }],
    'acropolis': [{ text: 'acro', cls: 'root-primary' }, { text: 'polis', cls: 'root-secondary' }],
    'democracy': [{ text: 'demo', cls: 'root-primary' }, { text: 'cracy', cls: 'root-secondary' }],
    'mythology': [{ text: 'myth', cls: 'root-primary' }, { text: 'ology', cls: 'root-secondary' }],
};
